openapi: 3.0.1
servers:
  - url: 'https://api.uve.demo.ubirch.com/'
    description: Universal Verification Endpoint - STAGING API server. Works only with DCCs signed with DEMO keys.
  - url: 'https://api.uve.ubirch.com/'
    description: Universal Verification Endpoint - PRODUCTION API server.
info:
  title: Universal Verification Endpoint API
  description: |
    Universal Verification Endpoint (UVE) to verify EU Digital Covid Certificates (DCC).

    ```
    Copyright (C) 2021 UBIRCH GmbH

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
    ```
  version: 1.0.0
  license:
    name: 'Apache License, Version 2.0'
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  contact:
    name: UBIRCH GmbH
    url: 'https://ubirch.com'
    email: uve-support@ubirch.com
paths:
  /api/uve/v1/verify:
    post:
      tags:
        - Verification
      summary: Verify a digital health certificate for authenticity.
      description: |
        # Description

        Checks the signature and verifies the authenticity of a Digital Covid Certificate (DCC).

        Requires mTLS-authentication with a X509 certificate.
      parameters:
        - in: header
          name: X-Transaction-Id
          description: A random and unique transaction id for every request against the api used for accounting generated by the user.
          schema:
            type: string
          example: 2b98009c-d4f6-11eb-8a22-1e00312e7f59
          required: true
        - in: header
          name: X-Transaction-Tag
          description: An optional random tag used for accounting specified by the user.
          schema:
            type: string
          example: HAM-Termninal-1
          required: false
        - in: header
          name: X-Verify-For
          description: |
            An optional value that specifies the jurisdiction to check. It supports EU and NHS.
            If no value or header is provided, EU is assumed by default. The accepted values are EU or NHS.
          schema:
            type: string
            enum: [EU, NHS]
          example: NHS
          required: false
        - schema:
            type: string
          in: header
          name: X-Forwarded-Tls-Client-Cert
          description: X509 pem string. It has to be a chained certificate as comma-separated string.
      requestBody:
        description: The encoded representation of a certificate.
        content:
          application/cbor+base45:
            schema:
              $ref: '#/components/schemas/CertificateEncoded'
      responses:
        '200':
          description: Certificate is authentic.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigicalCovidCertificate'
        '400':
          description: Invalid certificate
        '406':
          description: Incorrect data model
        '500':
          description: Internal Server Error
  /api/uve/v1/register-bootstrap-token:
    post:
      summary: Registers bootstrap token
      description: Register a bootstrap token for Tenant
      tags: []
      parameters:
        - schema:
            type: string
          in: header
          name: X-Forwarded-Tls-Client-Cert
          description: X509 pem string. It has to be a chained certificate as comma-separated string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            examples:
              string:
                value: string
        description: Bootstrap token
      responses:
        '200':
          description: Registration successful
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
components:
  schemas:
    DigicalCovidCertificate:
      $ref: schema/DCC.combined-schema.json
    CertificateEncoded:
      description: Base45 encoded and compressed Digital Corona Certificate (DCC) according to EU specification. An encoded certificate can be directly rendered as a QR code according to the EU specification.
      type: string
      format: base45
      example: 'HC1:6BFMX1.-N3PO0008GSJ31*SGP96B$0.-8$SQ6H865IQ0GP222J8-O0QJM9+V5K47YMCDC0KC8UQUC05A22WHY/G9-4LI1QJ0$BE%NRV%G21O5IVYCRU906N764PDY8*JBJ7GKOA2+EVHS7+T1 S0OF6:SJ%VPDEM2P59CQMBIQTCSIP/0ZPP799/W8X74EOCT6H5BKGS0-WJR5Q+:SOT7JK5UQ49HP*/Q1*S57TB$QH*OGVB:DN776KT80-3E9I.H4M U5.C30PU$CAMF+T9Y2QWQ1X4RZUH2PNF0A:3HJO0S6AD515J35RM.C8S3HKQ29 G+OQ44LOLJ+20H-3374Z.EG3H$E4112S22$MPLG7%OICKGEI1YC6QRV90B% 7/OMCNRS7BNJ19W1F$Q7ZKL6AVILQQM4ME$WGUHA845W2H2ZK*4NKDQ6VF29O:SHPNPFHN+U0$DTPBRR-MF1FSRB+93+*2U6V/RI$9SMWOBORN0OOHFNITC:7QHJ+6ER.7BOA1069CO58HUFBP37*+09NT/0'

